version: '3.8'
services:
  dbt_container:
    container_name: dbt_container
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      # - /home/constant/Documents/quests/docker_dbt/dbt_project:/usr/app
      # - /home/constant/Documents/quests/docker_dbt/profiles.yml:/root/.dbt/profiles.yml
       - .:/usr/app
       - ../profiles.yml:/root/.dbt/profiles.yml
    ports:
      - "4000:4000"
    tty: true # equivalent for -t
    stdin_open: true # equivalent for -i